name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.1.0'

permissions:
  contents: write

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Package .exe
        run: |
          mkdir -p dist
          cp target/release/lulu-ui.exe dist/lulu-ui.exe
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/lulu-ui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MUSL tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install GNU target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/lulu-ui dist/lulu-ui-linux-x86_64

      - uses: softprops/action-gh-release@v1
        with:
          files: dist/lulu-ui-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies for cross-compilation
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Add ARM64 GNU target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Build for aarch64
        env:
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          mkdir -p dist
          cp target/aarch64-unknown-linux-gnu/release/lulu-ui dist/lulu-ui-linux-aarch64

      - uses: softprops/action-gh-release@v1
        with:
          files: dist/lulu-ui-linux-aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Package
        run: |
          mkdir -p dist
          cp target/release/lulu-ui dist/lulu-ui-darwin
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/lulu-ui-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
